### ISSUE TITLE
Invalid Path creation on windows

### ISSUE THREAD

**Issue by imixtron** [Dvs-Bilisim/backup-manager#3]
Path are hardcoded to use `/`, which renders incorrect paths in windows OS.

For example **src/mongodb.js:28**
**Code**
```javascript
this.configure({ tmp: `${ this.options.path }/tmp/backup-${ Math.random().toString().replace('.', '') }` });
```

**Output**
- Path generated: `api\controllers\temp/development-2018-12-27T15:54:54.296Z.tar.gz`
- Path required: `api\controllers\temp\development-2018-12-27T15:54:54.296Z.tar.gz`

**Solution**
```javascript
const path = require('path');
const tmpPath = path.join(this.options.path, 'tmp', `backup-${ Math.random().toString().replace('.', '') }`);
this.configure({ tmp: tmpPath });
```

**Comment by umuplus** [comment]
None of us have been using this on windows. 
Thank you for your feedback. 

By the way, 0.5.x is broken from now on.
Building commands with options parameter was ugly. I replaced object implementation with arrays.
FYI
